### ISSUE TITLE
UML Diagram of sensitivity issue

### ISSUE THREAD

**Issue by empazi** [Lussebullen/terraform#5]
Key features affected by the issue are shown in UML class diagrams (for refactorings: include be-
fore/after).
Note: you do not have to show classes, fields, or methods that are not relevant, unless they help with
the overall understanding. Typically, the diagram would contain 5–10 classes.

DEPENDS ON: Specific issue resolution.

**Comment by emilsjol** [comment]
Relevant pull request merged, closing manually since pull request is to a fork.
